pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        // Репозиторий Yandex MapKit:
        maven { url "https://maven.yandex.net/repository/mobile-maps/" }
    }
}
rootProject.name = "ToiletsMoscow"
include ':app'
